language: android

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-21.1.1
    - extra
  
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

jdk: oraclejdk8

notifications:
 email: false

before_install:
    - sudo apt-get update -qq
    - chmod +x gradlew

script:
  - ./gradlew tasks --all
  - ./gradlew init
  - ./gradlew androidDependencies
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew assembleDebug
